# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/EntityFX.MqttSimulator
    - name: Build
      run: dotnet build --no-restore
      working-directory: src/EntityFX.MqttSimulator
    - name: Test
      run: dotnet test EntityFX.Tests.Integration.csproj --no-restore
      working-directory: src/EntityFX.MqttSimulator/EntityFX.Tests.Integration
    - name: Publish
      run:  dotnet publish src/EntityFX.MqttSimulator/EntityFX.MqttY.Cli/EntityFX.MqttY.Cli.csproj -c Release --no-restore
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: mqtty-net6.0
        path: src/EntityFX.MqttSimulator/EntityFX.MqttY.Cli/bin/Release/net6.0/publish/
